const BACKEND = "https://nexora-ai-cair.onrender.com";

let currentUser = { name: "Student" };
let notesContent = "";
let imageBase64 = "";
let imageMime = "";
let weeklyChart = null;
let pieChart = null;

// ── AUTH ──────────────────────────────────────────

function switchTab(tab) {
  document.getElementById("login-form").style.display = tab === "login" ? "block" : "none";
  document.getElementById("register-form").style.display = tab === "register" ? "block" : "none";
  document.querySelectorAll(".atab").forEach((el, i) => {
    el.classList.toggle("active", (i === 0 && tab === "login") || (i === 1 && tab === "register"));
  });
  clearMsg();
}

function showMsg(msg, type) {
  const el = document.getElementById("auth-msg");
  el.textContent = msg;
  el.className = "auth-msg " + type;
}

function clearMsg() {
  const el = document.getElementById("auth-msg");
  el.textContent = "";
  el.className = "auth-msg";
}

async function handleLogin() {
  const email = document.getElementById("login-email").value.trim();
  const password = document.getElementById("login-password").value.trim();
  if (!email || !password) return showMsg("Please fill all fields", "error");
  showMsg("Logging in...", "");
  try {
    const res = await fetch(`${BACKEND}/api/auth/login`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ email, password })
    });
    const data = await res.json();
    if (!res.ok) return showMsg(data.message, "error");
    localStorage.setItem("nexora_token", data.token);
    localStorage.setItem("nexora_user", JSON.stringify(data.user));
    currentUser = data.user;
    loadDashboard();
  } catch (err) {
    currentUser = { name: email.split("@")[0] };
    loadDashboard();
  }
}

async function handleRegister() {
  const name = document.getElementById("reg-name").value.trim();
  const email = document.getElementById("reg-email").value.trim();
  const password = document.getElementById("reg-password").value.trim();
  if (!name || !email || !password) return showMsg("Please fill all fields", "error");
  if (password.length < 6) return showMsg("Password must be at least 6 characters", "error");
  showMsg("Creating account...", "");
  try {
    const res = await fetch(`${BACKEND}/api/auth/register`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name, email, password })
    });
    const data = await res.json();
    if (!res.ok) return showMsg(data.message, "error");
    localStorage.setItem("nexora_token", data.token);
    localStorage.setItem("nexora_user", JSON.stringify(data.user));
    currentUser = data.user;
    loadDashboard();
  } catch (err) {
    currentUser = { name };
    loadDashboard();
  }
}

function loadDashboard() {
  document.getElementById("auth-screen").style.display = "none";
  document.getElementById("dashboard").style.display = "flex";
  const name = currentUser.name || "Student";
  const initial = name.charAt(0).toUpperCase();
  const hour = new Date().getHours();
  const greeting = hour < 12 ? "Good morning" : hour < 17 ? "Good afternoon" : "Good evening";
  document.getElementById("page-title").textContent = `${greeting}, ${name}!`;
  document.getElementById("page-sub").textContent = "What will you learn today?";
  document.getElementById("sf-name").textContent = name;
  document.getElementById("sf-avatar").textContent = initial;
  document.getElementById("user-circle").textContent = initial;
  updateStatsUI();
  loadPlans();
}

function handleLogout() {
  localStorage.removeItem("nexora_token");
  localStorage.removeItem("nexora_user");
  document.getElementById("dashboard").style.display = "none";
  document.getElementById("auth-screen").style.display = "flex";
  currentUser = { name: "Student" };
  notesContent = "";
  imageBase64 = "";
}

// ── NAVIGATION ────────────────────────────────────

const pageTitles = {
  home: ["Dashboard", "What will you learn today?"],
  doubt: ["Doubt solver", "Ask anything — get instant AI answers"],
  notes: ["AI notes", "Enter a topic, get perfect study notes"],
  code: ["Code helper", "Write, debug and understand code with AI"],
  test: ["Mock tests", "Practice questions generated by AI"],
  image: ["Image solver", "Upload a question photo — get instant solution"],
  planner: ["Study planner", "Plan your subjects and track daily progress"],
  resume: ["Resume builder", "Build your professional resume with AI"],
  career: ["Career guide", "AI career counsellor for Indian students"],
  analytics: ["Analytics", "Track your study performance and habits"]
};

function switchPanel(el, name) {
  document.querySelectorAll(".nav-item").forEach(n => n.classList.remove("active"));
  el.classList.add("active");
  document.querySelectorAll(".panel").forEach(p => p.classList.remove("active"));
  document.getElementById("panel-" + name).classList.add("active");
  document.getElementById("page-title").textContent = pageTitles[name][0];
  document.getElementById("page-sub").textContent = pageTitles[name][1];
  if (name === "analytics") setTimeout(() => renderAnalytics(), 100);
}

// ── AI HELPER ─────────────────────────────────────

async function askAI(system, message) {
  const res = await fetch(`${BACKEND}/api/ai/ask`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ system, message })
  });
  const data = await res.json();
  if (!data.result) throw new Error(data.message || "AI error");
  return data.result;
}

// ── ANALYTICS ─────────────────────────────────────

function getAnalytics() {
  const stored = localStorage.getItem("nexora_analytics");
  if (stored) return JSON.parse(stored);
  return {
    doubtsAsked: 0, notesGenerated: 0, testsAttempted: 0,
    correctAnswers: 0, totalAnswers: 0, studyStreak: 0,
    lastStudyDate: "", weeklyActivity: [0,0,0,0,0,0,0],
    topicsCompleted: [], dailyHeatmap: {}
  };
}

function saveAnalytics(a) {
  localStorage.setItem("nexora_analytics", JSON.stringify(a));
  updateStatsUI();
  syncAnalyticsToBackend(a);
}

async function syncAnalyticsToBackend(a) {
  const token = localStorage.getItem("nexora_token");
  if (!token) return;
  try {
    await fetch(`${BACKEND}/api/analytics/update`, {
      method: "POST",
      headers: { "Content-Type": "application/json", "Authorization": "Bearer " + token },
      body: JSON.stringify(a)
    });
  } catch (e) {}
}

function trackActivity(type, extra = {}) {
  const a = getAnalytics();
  const today = new Date().toISOString().split("T")[0];
  const dayIndex = new Date().getDay();
  if (type === "doubt") a.doubtsAsked += 1;
  if (type === "notes") {
    a.notesGenerated += 1;
    if (extra.topic && !a.topicsCompleted.includes(extra.topic)) a.topicsCompleted.push(extra.topic);
  }
  if (type === "test") {
    a.testsAttempted += 1;
    a.correctAnswers += extra.correct || 0;
    a.totalAnswers += extra.total || 0;
  }
  a.weeklyActivity[dayIndex] = (a.weeklyActivity[dayIndex] || 0) + 1;
  a.dailyHeatmap[today] = (a.dailyHeatmap[today] || 0) + 1;
  if (a.lastStudyDate !== today) {
    const yesterday = new Date();
    yesterday.setDate(yesterday.getDate() - 1);
    const yStr = yesterday.toISOString().split("T")[0];
    a.studyStreak = a.lastStudyDate === yStr ? a.studyStreak + 1 : 1;
    a.lastStudyDate = today;
  }
  saveAnalytics(a);
}

function updateStatsUI() {
  const a = getAnalytics();
  const accuracy = a.totalAnswers > 0 ? Math.round((a.correctAnswers / a.totalAnswers) * 100) : 0;
  const g = (id) => document.getElementById(id);
  if (g("stat-doubts")) g("stat-doubts").textContent = a.doubtsAsked;
  if (g("stat-notes")) g("stat-notes").textContent = a.notesGenerated;
  if (g("stat-tests")) g("stat-tests").textContent = a.testsAttempted;
  if (g("stat-accuracy")) g("stat-accuracy").textContent = accuracy + "%";
  if (g("top-streak")) g("top-streak").textContent = a.studyStreak;
}

function renderAnalytics() {
  const a = getAnalytics();
  const accuracy = a.totalAnswers > 0 ? Math.round((a.correctAnswers / a.totalAnswers) * 100) : 0;

  const wCtx = document.getElementById("weekly-chart");
  if (wCtx) {
    if (weeklyChart) weeklyChart.destroy();
    weeklyChart = new Chart(wCtx, {
      type: "bar",
      data: {
        labels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        datasets: [{
          label: "Activity",
          data: a.weeklyActivity,
          backgroundColor: "#7F77DD",
          borderRadius: 6,
          borderSkipped: false
        }]
      },
      options: {
        responsive: true,
        plugins: { legend: { display: false } },
        scales: {
          y: { beginAtZero: true, grid: { color: "rgba(0,0,0,0.04)" }, ticks: { stepSize: 1 } },
          x: { grid: { display: false } }
        }
      }
    });
  }

  const pCtx = document.getElementById("pie-chart");
  if (pCtx) {
    if (pieChart) pieChart.destroy();
    pieChart = new Chart(pCtx, {
      type: "doughnut",
      data: {
        labels: ["Doubts", "Notes", "Tests"],
        datasets: [{
          data: [a.doubtsAsked || 0, a.notesGenerated || 0, a.testsAttempted || 0],
          backgroundColor: ["#7F77DD", "#1D9E75", "#D85A30"],
          borderWidth: 0
        }]
      },
      options: {
        responsive: true, cutout: "70%",
        plugins: { legend: { position: "bottom", labels: { padding: 16, font: { size: 12 } } } }
      }
    });
  }

  const perf = document.getElementById("perf-stats");
  if (perf) {
    perf.innerHTML = `
      <div class="perf-row"><span class="perf-label">Study streak</span><span class="perf-val" style="color:#EF9F27">${a.studyStreak} days</span></div>
      <div class="perf-row"><span class="perf-label">Accuracy</span><span class="perf-val" style="color:#7F77DD">${accuracy}%</span></div>
      <div class="perf-row"><span class="perf-label">Total doubts</span><span class="perf-val">${a.doubtsAsked}</span></div>
      <div class="perf-row"><span class="perf-label">Notes created</span><span class="perf-val">${a.notesGenerated}</span></div>
      <div class="perf-row"><span class="perf-label">Tests taken</span><span class="perf-val">${a.testsAttempted}</span></div>
      <div class="perf-row"><span class="perf-label">Correct answers</span><span class="perf-val" style="color:#1D9E75">${a.correctAnswers}</span></div>
      <div class="perf-row"><span class="perf-label">Topics covered</span><span class="perf-val">${a.topicsCompleted.length}</span></div>
    `;
  }

  const hmap = document.getElementById("heatmap");
  if (hmap) {
    hmap.innerHTML = "";
    for (let i = 29; i >= 0; i--) {
      const d = new Date();
      d.setDate(d.getDate() - i);
      const key = d.toISOString().split("T")[0];
      const count = a.dailyHeatmap[key] || 0;
      const cell = document.createElement("div");
      const level = count === 0 ? "" : count < 3 ? " hmap-1" : count < 6 ? " hmap-2" : count < 10 ? " hmap-3" : " hmap-4";
      cell.className = "hmap-cell" + level;
      cell.title = `${key}: ${count} activities`;
      hmap.appendChild(cell);
    }
  }

  const topicsList = document.getElementById("topics-list");
  if (topicsList) {
    topicsList.innerHTML = a.topicsCompleted.length === 0
      ? '<p style="font-size:13px;color:var(--hint)">No topics completed yet — generate notes to track topics</p>'
      : a.topicsCompleted.map(t => `<div class="topic-chip">${t}</div>`).join("");
  }
}

// ── DOUBT SOLVER ──────────────────────────────────

async function sendDoubt() {
  const input = document.getElementById("doubt-input");
  const msg = input.value.trim();
  if (!msg) return;
  input.value = "";
  appendBubble(msg, "user", "chat-messages");
  showTyping("chat-messages", "ai");
  trackActivity("doubt");
  try {
    const reply = await askAI(
      `You are Nexora AI, a friendly study assistant for Indian college students.
       Answer doubts clearly and concisely. Use simple language with real-life examples.
       Use **bold** for important terms. Keep answers under 200 words unless needed.`,
      msg
    );
    removeTyping("chat-messages");
    appendBubble(reply, "ai", "chat-messages");
  } catch (err) {
    removeTyping("chat-messages");
    appendBubble("Sorry, something went wrong. Please make sure the backend is running.", "ai", "chat-messages");
  }
}

function appendBubble(text, type, areaId) {
  const area = document.getElementById(areaId);
  const wrap = document.createElement("div");
  wrap.className = `bubble-wrap ${type === "user" ? "user" : ""}`;
  const avatar = document.createElement("div");
  const isCareer = areaId === "career-messages";
  avatar.className = `bub-avatar ${type === "ai" ? (isCareer ? "career-av" : "ai-av") : "usr-av"}`;
  avatar.innerHTML = type === "ai"
    ? (isCareer ? '<i class="ti ti-briefcase"></i>' : '<i class="ti ti-brain"></i>')
    : currentUser.name.charAt(0).toUpperCase();
  const bubble = document.createElement("div");
  bubble.className = `bubble ${type === "ai" ? (isCareer ? "career-bubble" : "ai-bubble") : "usr-bubble"}`;
  bubble.innerHTML = text.replace(/\n/g, "<br>").replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>");
  wrap.appendChild(avatar);
  wrap.appendChild(bubble);
  area.appendChild(wrap);
  area.scrollTop = area.scrollHeight;
}

function showTyping(areaId, type) {
  const area = document.getElementById(areaId);
  const wrap = document.createElement("div");
  wrap.className = "bubble-wrap";
  wrap.id = "typing-" + areaId;
  const avatar = document.createElement("div");
  avatar.className = `bub-avatar ${type === "career" ? "career-av" : "ai-av"}`;
  avatar.innerHTML = type === "career" ? '<i class="ti ti-briefcase"></i>' : '<i class="ti ti-brain"></i>';
  const bubble = document.createElement("div");
  bubble.className = "bubble ai-bubble";
  bubble.innerHTML = '<div class="typing-dots"><div class="dot"></div><div class="dot"></div><div class="dot"></div></div>';
  wrap.appendChild(avatar);
  wrap.appendChild(bubble);
  area.appendChild(wrap);
  area.scrollTop = area.scrollHeight;
}

function removeTyping(areaId) {
  const el = document.getElementById("typing-" + areaId);
  if (el) el.remove();
}

// ── NOTES ─────────────────────────────────────────

async function generateNotes() {
  const topic = document.getElementById("notes-topic").value.trim();
  if (!topic) return;
  const output = document.getElementById("notes-output");
  output.innerHTML = `<div class="loading"><div class="dot"></div><div class="dot"></div><div class="dot"></div>&nbsp; Generating notes for <strong>${topic}</strong>...</div>`;
  document.getElementById("notes-actions").style.display = "none";
  try {
    const result = await askAI(
      `You are Nexora AI notes generator for Indian college students.
       Generate clean structured study notes.
       Format EXACTLY:
       SECTION: [Title in caps]
       CONTENT: [Content here]
       Include 5-6 sections. End with SECTION: KEY POINTS listing the most important facts.`,
      `Generate detailed study notes for: ${topic}`
    );
    notesContent = result;
    trackActivity("notes", { topic });
    renderNotes(result, topic);
    document.getElementById("notes-actions").style.display = "flex";
  } catch (err) {
    output.innerHTML = '<div class="empty-state"><i class="ti ti-alert-circle"></i><p>Error generating notes. Make sure backend is running.</p></div>';
  }
}

function renderNotes(text, topic) {
  const output = document.getElementById("notes-output");
  let html = `<div class="notes-heading">${topic} — complete notes</div>`;
  text.split("\n").forEach(line => {
    const t = line.trim();
    if (t.startsWith("SECTION:")) html += `<div class="notes-section-title">${t.replace("SECTION:", "").trim()}</div>`;
    else if (t.startsWith("CONTENT:")) html += `<div class="notes-text">${t.replace("CONTENT:", "").trim()}</div>`;
    else if (t) html += `<div class="notes-text">${t}</div>`;
  });
  output.innerHTML = html;
}

function copyNotes() {
  navigator.clipboard.writeText(notesContent);
  alert("Notes copied!");
}

function downloadNotes() {
  const topic = document.getElementById("notes-topic").value || "notes";
  const blob = new Blob([notesContent], { type: "text/plain" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = `nexora-${topic.replace(/\s+/g, "-")}.txt`;
  a.click();
}

// ── CODE HELPER ───────────────────────────────────

async function runCodeHelper() {
  const input = document.getElementById("code-input").value.trim();
  if (!input) return;
  const output = document.getElementById("code-output");
  output.innerHTML = '<div class="loading"><div class="dot"></div><div class="dot"></div><div class="dot"></div>&nbsp; Analyzing your code...</div>';
  try {
    const result = await askAI(
      `You are Nexora AI code helper for college students.
       When given code: explain it, fix errors, suggest improvements.
       When given a description: write clean working code with comments.
       Format EXACTLY:
       CODE:
       [complete code here]
       EXPLANATION:
       [simple explanation]`,
      input
    );
    renderCode(result);
  } catch (err) {
    output.innerHTML = '<div class="empty-state"><i class="ti ti-alert-circle"></i><p>Error. Make sure backend is running.</p></div>';
  }
}

function renderCode(text) {
  const output = document.getElementById("code-output");
  const parts = text.split("EXPLANATION:");
  const codePart = parts[0].replace("CODE:", "").trim();
  const explainPart = parts[1] ? parts[1].trim() : "";
  let html = `<pre class="code-result">${escapeHtml(codePart)}</pre>`;
  if (explainPart) html += `<div class="code-explain"><strong>Explanation:</strong><br>${explainPart.replace(/\n/g, "<br>")}</div>`;
  output.innerHTML = html;
}

function escapeHtml(text) {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

// ── MOCK TESTS ────────────────────────────────────

async function generateTest() {
  const topic = document.getElementById("test-topic").value.trim();
  const difficulty = document.getElementById("test-difficulty").value;
  if (!topic) return;
  const output = document.getElementById("test-output");
  output.innerHTML = '<div class="loading"><div class="dot"></div><div class="dot"></div><div class="dot"></div>&nbsp; Generating mock test...</div>';
  try {
    const result = await askAI(
      `You are Nexora AI mock test generator for Indian college students.
       Generate exactly 5 multiple choice questions.
       Format EXACTLY like this for each question:
       Q: [question]
       A: [option 1]
       B: [option 2]
       C: [option 3]
       D: [option 4]
       ANS: [correct letter A B C or D]
       Separate each question with ---
       Output ONLY questions in the format above, nothing else.`,
      `Generate ${difficulty} difficulty mock test on: ${topic}`
    );
    renderTest(result);
  } catch (err) {
    output.innerHTML = '<div class="empty-state"><i class="ti ti-alert-circle"></i><p>Error generating test. Make sure backend is running.</p></div>';
  }
}

function renderTest(text) {
  const output = document.getElementById("test-output");
  const questions = text.split("---").filter(q => q.trim());
  let html = "";
  questions.forEach((q, idx) => {
    const lines = q.trim().split("\n").filter(l => l.trim());
    const get = (p) => lines.find(l => l.startsWith(p))?.replace(p, "").trim() || "";
    html += `
      <div class="quiz-question" data-ans="${get("ANS:")}" id="q${idx}">
        <div class="quiz-q-title">Q${idx + 1}. ${get("Q:")}</div>
        <label class="quiz-option"><input type="radio" name="q${idx}" value="A"> ${get("A:")}</label>
        <label class="quiz-option"><input type="radio" name="q${idx}" value="B"> ${get("B:")}</label>
        <label class="quiz-option"><input type="radio" name="q${idx}" value="C"> ${get("C:")}</label>
        <label class="quiz-option"><input type="radio" name="q${idx}" value="D"> ${get("D:")}</label>
      </div>`;
  });
  html += `<button onclick="submitTest(${questions.length})" class="gen-btn coral-btn" style="width:100%;justify-content:center;margin-top:4px"><i class="ti ti-check"></i> Submit answers</button>`;
  output.innerHTML = html;
}

function submitTest(total) {
  let score = 0;
  for (let i = 0; i < total; i++) {
    const selected = document.querySelector(`input[name="q${i}"]:checked`)?.value;
    const correct = document.getElementById(`q${i}`)?.dataset.ans;
    const qEl = document.getElementById(`q${i}`);
    if (!qEl) continue;
    if (selected === correct) {
      score++;
      qEl.style.borderColor = "#1D9E75";
      qEl.style.background = "#E1F5EE";
    } else {
      qEl.style.borderColor = "#E24B4A";
      qEl.style.background = "#FCEBEB";
    }
  }
  trackActivity("test", { correct: score, total });
  const result = document.createElement("div");
  result.style = "text-align:center;padding:16px;font-size:16px;font-weight:800;color:var(--purple)";
  result.textContent = `Your score: ${score} / ${total} 🎉`;
  document.getElementById("test-output").appendChild(result);
  document.getElementById("test-output").scrollTop = 99999;
}

// ── IMAGE SOLVER ──────────────────────────────────

function handleImageUpload(event) {
  const file = event.target.files[0];
  if (!file) return;
  imageMime = file.type;
  const reader = new FileReader();
  reader.onload = (e) => {
    imageBase64 = e.target.result.split(",")[1];
    document.getElementById("image-preview").src = e.target.result;
    document.getElementById("image-preview-wrap").style.display = "flex";
    document.getElementById("image-upload-area").style.display = "none";
    document.getElementById("image-output").innerHTML = '<div class="empty-state"><i class="ti ti-camera"></i><p>Click "Solve this question" to get the answer</p></div>';
  };
  reader.readAsDataURL(file);
}

function resetImage() {
  imageBase64 = "";
  imageMime = "";
  document.getElementById("image-preview-wrap").style.display = "none";
  document.getElementById("image-upload-area").style.display = "block";
  document.getElementById("image-file-input").value = "";
  document.getElementById("image-output").innerHTML = '<div class="empty-state"><i class="ti ti-camera"></i><p>Upload an image of your question above</p></div>';
}

async function solveImage() {
  if (!imageBase64) return;
  const output = document.getElementById("image-output");
  output.innerHTML = '<div class="loading"><div class="dot"></div><div class="dot"></div><div class="dot"></div>&nbsp; Analyzing your question...</div>';
  try {
    const res = await fetch(`${BACKEND}/api/ai/image`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ imageBase64, mimeType: imageMime })
    });
    const data = await res.json();
    if (!data.result) throw new Error("No result");
    output.innerHTML = `<div class="notes-heading">Solution</div><div class="notes-text" style="line-height:1.8">${data.result.replace(/\n/g, "<br>").replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")}</div>`;
    trackActivity("doubt");
  } catch (err) {
    output.innerHTML = '<div class="empty-state"><i class="ti ti-alert-circle"></i><p>Error solving image. Make sure backend is running.</p></div>';
  }
}

// ── STUDY PLANNER ─────────────────────────────────

async function generatePlanWithAI() {
  const subject = document.getElementById("plan-subject").value.trim();
  const examDate = document.getElementById("plan-examdate").value;
  if (!subject) return alert("Please enter a subject name");
  try {
    const result = await askAI(
      `You are Nexora AI study planner for Indian college students.
       Generate a study plan as a list of topics.
       Return ONLY a JSON array of topic strings, nothing else, no markdown.
       Example: ["Introduction","Core Concepts","Advanced Topics","Practice"]
       Generate 8-12 topics for the subject.`,
      `Generate study plan topics for: ${subject}`
    );
    let topics = [];
    try {
      topics = JSON.parse(result.replace(/```json|```/g, "").trim());
    } catch (e) {
      topics = result.split("\n").filter(t => t.trim()).map(t => t.replace(/^[-*\d.]+\s*/, "").trim()).filter(Boolean);
    }
    await savePlan(subject, topics, examDate);
  } catch (err) {
    alert("Error generating plan. Make sure backend is running.");
  }
}

async function savePlan(subject, topics, examDate) {
  const token = localStorage.getItem("nexora_token");
  if (token) {
    try {
      await fetch(`${BACKEND}/api/plan/create`, {
        method: "POST",
        headers: { "Content-Type": "application/json", "Authorization": "Bearer " + token },
        body: JSON.stringify({ subject, topics, examDate })
      });
      loadPlans();
      return;
    } catch (e) {}
  }
  const plans = JSON.parse(localStorage.getItem("nexora_plans") || "[]");
  plans.unshift({
    _id: Date.now().toString(),
    subject, examDate,
    topics: topics.map(t => ({ title: t, completed: false })),
    createdAt: new Date().toISOString()
  });
  localStorage.setItem("nexora_plans", JSON.stringify(plans));
  loadPlans();
}

async function loadPlans() {
  const token = localStorage.getItem("nexora_token");
  let plans = [];
  if (token) {
    try {
      const res = await fetch(`${BACKEND}/api/plan/get`, {
        headers: { "Authorization": "Bearer " + token }
      });
      plans = await res.json();
    } catch (e) {
      plans = JSON.parse(localStorage.getItem("nexora_plans") || "[]");
    }
  } else {
    plans = JSON.parse(localStorage.getItem("nexora_plans") || "[]");
  }
  renderPlans(plans);
}

function renderPlans(plans) {
  const list = document.getElementById("plans-list");
  if (!plans || plans.length === 0) {
    list.innerHTML = '<div class="empty-state"><i class="ti ti-calendar"></i><p>Create your first study plan above</p></div>';
    return;
  }
  list.innerHTML = plans.map(plan => {
    const total = plan.topics.length;
    const done = plan.topics.filter(t => t.completed).length;
    const pct = total > 0 ? Math.round((done / total) * 100) : 0;
    const topicsHTML = plan.topics.map((t, i) => `
      <div class="plan-topic ${t.completed ? "done" : ""}" onclick="toggleTopic('${plan._id}',${i})">
        <i class="ti ${t.completed ? "ti-circle-check" : "ti-circle"}"></i>${t.title}
      </div>`).join("");
    return `
      <div class="plan-card" id="plan-${plan._id}">
        <div class="plan-header">
          <div>
            <div class="plan-subject">${plan.subject}</div>
            <div class="plan-meta">${done}/${total} topics · ${pct}% complete${plan.examDate ? " · Exam: " + plan.examDate : ""}</div>
          </div>
          <button class="plan-delete" onclick="deletePlan('${plan._id}')"><i class="ti ti-trash"></i></button>
        </div>
        <div class="plan-progress"><div class="plan-progress-fill" style="width:${pct}%"></div></div>
        <div class="plan-topics">${topicsHTML}</div>
      </div>`;
  }).join("");
}

async function toggleTopic(planId, topicIndex) {
  const token = localStorage.getItem("nexora_token");
  if (token) {
    try {
      await fetch(`${BACKEND}/api/plan/toggle`, {
        method: "POST",
        headers: { "Content-Type": "application/json", "Authorization": "Bearer " + token },
        body: JSON.stringify({ planId, topicIndex })
      });
      loadPlans();
      return;
    } catch (e) {}
  }
  const plans = JSON.parse(localStorage.getItem("nexora_plans") || "[]");
  const plan = plans.find(p => p._id === planId);
  if (plan) {
    plan.topics[topicIndex].completed = !plan.topics[topicIndex].completed;
    localStorage.setItem("nexora_plans", JSON.stringify(plans));
    renderPlans(plans);
  }
}

async function deletePlan(planId) {
  const token = localStorage.getItem("nexora_token");
  if (token) {
    try {
      await fetch(`${BACKEND}/api/plan/${planId}`, {
        method: "DELETE",
        headers: { "Authorization": "Bearer " + token }
      });
      loadPlans();
      return;
    } catch (e) {}
  }
  const plans = JSON.parse(localStorage.getItem("nexora_plans") || "[]").filter(p => p._id !== planId);
  localStorage.setItem("nexora_plans", JSON.stringify(plans));
  renderPlans(plans);
}

// ── RESUME BUILDER ────────────────────────────────

async function generateResume() {
  const userData = {
    name: document.getElementById("r-name").value.trim(),
    email: document.getElementById("r-email").value.trim(),
    phone: document.getElementById("r-phone").value.trim(),
    location: document.getElementById("r-location").value.trim(),
    linkedin: document.getElementById("r-linkedin").value.trim(),
    github: document.getElementById("r-github").value.trim(),
    college: document.getElementById("r-college").value.trim(),
    degree: document.getElementById("r-degree").value.trim(),
    year: document.getElementById("r-year").value.trim(),
    cgpa: document.getElementById("r-cgpa").value.trim(),
    skills: document.getElementById("r-skills").value.trim(),
    projects: document.getElementById("r-projects").value.trim(),
    experience: document.getElementById("r-experience").value.trim(),
    achievements: document.getElementById("r-achievements").value.trim(),
    objective: document.getElementById("r-objective").value.trim()
  };
  if (!userData.name || !userData.email || !userData.college) {
    return alert("Please fill in at least name, email and college");
  }
  const output = document.getElementById("resume-output");
  output.innerHTML = '<div class="loading"><div class="dot"></div><div class="dot"></div><div class="dot"></div>&nbsp; Building your resume...</div>';
  try {
    const res = await fetch(`${BACKEND}/api/ai/resume`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ userData })
    });
    const data = await res.json();
    if (!data.result) throw new Error("No result");
    output.innerHTML = data.result;
  } catch (err) {
    output.innerHTML = '<div class="empty-state"><i class="ti ti-alert-circle"></i><p>Error generating resume. Make sure backend is running.</p></div>';
  }
}

function downloadResume() {
  const output = document.getElementById("resume-output");
  if (!output.innerHTML || output.querySelector(".empty-state")) {
    return alert("Please generate your resume first");
  }
  const printWindow = window.open("", "_blank");
  printWindow.document.write(`<!DOCTYPE html><html><head><title>Resume — Nexora AI</title>
    <style>body{font-family:Arial,sans-serif;margin:0;padding:20px}@media print{body{margin:0;padding:0}}</style>
    </head><body>${output.innerHTML}</body></html>`);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => { printWindow.print(); printWindow.close(); }, 500);
}

// ── CAREER GUIDE ──────────────────────────────────

async function sendCareerMsg() {
  const input = document.getElementById("career-input");
  const msg = input.value.trim();
  if (!msg) return;
  input.value = "";
  appendBubble(msg, "user", "career-messages");
  showTyping("career-messages", "career");
  try {
    const reply = await askAI(
      `You are Nexora Career Guide, an expert career counsellor for Indian college students.
       Give honest, practical, India-specific career advice.
       Cover: jobs, salaries, skills, certifications, internships, placements, higher studies, freelancing.
       Be direct and specific — mention real companies, real salary ranges, real platforms.
       Use **bold** for important points. Keep responses clear and under 300 words.
       Always be encouraging and realistic about Indian job market.`,
      msg
    );
    removeTyping("career-messages");
    appendBubble(reply, "ai", "career-messages");
  } catch (err) {
    removeTyping("career-messages");
    appendBubble("Sorry, something went wrong. Please make sure the backend is running.", "ai", "career-messages");
  }
}

function askCareerTopic(topic) {
  document.getElementById("career-input").value = topic;
  sendCareerMsg();
}

// ── INIT ──────────────────────────────────────────

window.onload = () => {
  const token = localStorage.getItem("nexora_token");
  const user = localStorage.getItem("nexora_user");
  if (token && user) {
    currentUser = JSON.parse(user);
    loadDashboard();
  }
};